version: '3'
services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=Admin'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=db_zad5'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080